### ISSUE TITLE
DB initialization fails because DB is not define

### ISSUE THREAD

**Issue by bnestelroad** [playniuniu/docker-ansible-semaphore#2]
While attempting to run this container for the first time I ran into an issue with the database initialization step.  I discovered that in the entrypoint.sh file the following line was not executing properly:

`until mysql -h ${SEMAPHORE_DB_HOST} -u ${SEMAPHORE_DB_USER} --password=${SEMAPHORE_DB_PASS} ${SEMAPHORE_DB} -e "select version();" &>/dev/null;`

I found that on line 4 you are trying to log into the mariadb server and semaphore database before the database itself has been created.  That then causes the container to sit and wait for a connection to a database that does not exist and cannot be created.

I modified the script by removing `${SEMAPHORE_DB}` and the script was able to initialize the database.  After the initial database initialization it is safe to put the check back in and things run fine.

**Comment by playniuniu** [comment]
Hi bnestelroad, thanks for your suggestion

I will check it, now it seems  [Semaphore](https://github.com/ansible-semaphore/semaphore) have official Dockerfile to build images, so maybe I will not maintain this repo anymore
